version: '2'

services:
  mysqld:
    image: mysql:5.7
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  markdown:
    image: serlo/athene2-editor:v0.0.2

  athene2:
    build: .
    links:
      - mysqld:mysqld
      - markdown:markdown
    ports:
      - '4567:80'
    volumes:
      - ./src/config:/var/www/html/src/config
      - ./src/lang:/var/www/html/src/lang
      - ./src/module:/var/www/html/src/module
      - ./src/public:/var/www/html/src/public
      - ./src/test:/var/www/html/src/test
      - ./src/vendor:/var/www/html/src/vendor
    environment:
      - PHP_ENV=development

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysqld:db
    ports:
      - '8080:80'
